# Generated by Django 3.2.24 on 2025-05-16 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dttotDocReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DttotDocReportCorporate',
            fields=[
                ('dttotdoc_report_corporate_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='DTTOT Doc Report Corporate ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Created Date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Entry Updated Date')),
                ('dsb_user_corporate', models.CharField(blank=True, max_length=255, verbose_name='Entry Corporate User that matched with similarity > 0.8')),
                ('kode_densus_corporate', models.CharField(blank=True, max_length=20, verbose_name='Entry Corporate User that matched with similarity > 0.8')),
                ('score_match_similarity', models.FloatField(default=0.0, verbose_name='Similarity Score')),
                ('dttotdoc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_reports', related_query_name='corporate_report', to='dttotDocReport.dttotdocreport')),
            ],
            options={
                'verbose_name': 'DTTOT Data from User Corporate',
                'verbose_name_plural': 'Multi DTTOT Data from User Corporate',
                'db_table': 'dttotdoc_corporate',
            },
        ),
    ]
