# Generated by Django 3.2.24 on 2025-05-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dttotDocReportCorporate', '0002_dttotdocreportcorporate_last_update_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dttotdocreportcorporate',
            table='dttotdocreport_corporate',
        ),
    ]
