# Generated by Django 3.2.24 on 2025-05-27 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dttotDocReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DttotDocReportPublisher',
            fields=[
                ('dttotdoc_report_publisher_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='DTTOT Doc Report Publisher ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Created Date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Entry Updated Date')),
                ('dsb_user_publisher', models.CharField(blank=True, max_length=255, verbose_name='User Publisher ID')),
                ('kode_densus_publisher', models.CharField(blank=True, max_length=20, verbose_name='Entry Personal User that matched with similarity > 0.8')),
                ('score_match_similarity', models.FloatField(default=0.0, verbose_name='Similarity Score')),
                ('dttotdoc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_reports', related_query_name='publisher_report', to='dttotDocReport.dttotdocreport')),
            ],
            options={
                'verbose_name': 'DTTOT Doc Report from User Publisher',
                'verbose_name_plural': 'Multi DTTOT Doc Report from User Publisher',
                'db_table': 'dttotdocreport_publisher',
            },
        ),
    ]
