# Generated by Django 3.2.24 on 2025-05-16 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dttotDocReportPublisher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dttotdocreportpublisher',
            name='last_update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dttotDoc_publishers', related_query_name='updated_dttotDoc_publisher', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by User'),
        ),
    ]
