version: "3.9"

x-common: &common
  env_file:
    - '.env'
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  networks:
    - main

services:
  app:
    <<: *common
    build:
      context: .
      args:
        DEV: true
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_PORT: ${DB_PORT}
        DJANGO_USER: ${DJANGO_USER}
        DJANGO_UID: ${DJANGO_UID}
        DJANGO_GID: ${DJANGO_GID}
    environment:
      WORKERS: ${WORKERS:-2}
      THREADS: ${THREADS:-2}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/apps
      - logs:/apps/logs
    command: make run.server.prod
    depends_on:
      - pgbouncer
      - redis
      - rabbitmq
      - collectstatic

  db:
    <<: *common
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: --auth=md5
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  pgbouncer:
    <<: *common
    image: bitnami/pgbouncer:1-debian-12
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=5
      - RESERVE_POOL_SIZE=5
      - RESERVE_POOL_TIMEOUT=5
      - SERVER_RESET_QUERY=DISCARD ALL
      - SERVER_CHECK_QUERY=select 1
      - LOG_CONNECTIONS=1
      - LOG_DISCONNECTIONS=1
      - LOG_POOLER_ERRORS=1
      - STATS_PERIOD=60
      - AUTH_TYPE=md5
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - pgbouncer-data:/var/lib/pgbouncer

  redis:
    <<: *common
    image: redis:7.2.5-bookworm
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru

  rabbitmq:
    <<: *common
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_DASHBOARD_PORT}:15672"

  celery:
    <<: *common
    build:
      context: .
      args:
        - DEV=true
        - DJANGO_USER=${DJANGO_USER}
        - DJANGO_UID=${DJANGO_UID}
        - DJANGO_GID=${DJANGO_GID}
    command: make run.celery.prod
    restart: unless-stopped
    depends_on:
      - app
      - redis
      - rabbitmq
    volumes:
      - ./backend:/apps
      - logs:/apps/logs

  celery-beat:
    <<: *common
    build:
      context: .
      args:
        - DEV=true
        - DJANGO_USER=${DJANGO_USER}
        - DJANGO_UID=${DJANGO_UID}
        - DJANGO_GID=${DJANGO_GID}
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BEAT_SLEEP_INTERVAL=${CELERY_BEAT_SLEEP_INTERVAL}
    command: make run.celery.beat.prod
    restart: no
    depends_on:
      - app
      - redis
      - rabbitmq
    volumes:
      - ./backend:/apps
      - logs:/apps/logs

  collectstatic:
    <<: *common
    build:
      context: .
      args:
        - DEV=true
        - DJANGO_USER=${DJANGO_USER}
        - DJANGO_UID=${DJANGO_UID}
        - DJANGO_GID=${DJANGO_GID}
    command: make collectstatic
    depends_on:
      - db
    volumes:
      - ./backend:/apps

  smtp:
    <<: *common
    build:
      context: .
      args:
        - DEV=true
        - DJANGO_USER=${DJANGO_USER}
        - DJANGO_UID=${DJANGO_UID}
        - DJANGO_GID=${DJANGO_GID}
    command: >
      sh -c "python -m aiosmtpd -n -l 0.0.0.0:8025"
    ports:
      - "8025:8025"
    volumes:
      - ./backend:/apps

networks:
  main:
    ipam:
      driver: default

volumes:
  dev-db-data:
  pgbouncer-data:
  redis-data:
  rabbitmq-data:
  logs:
