# Generated by Django 3.2.24 on 2024-09-03 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_tracker_publisher',
            fields=[
                ('log_tracker_publisher_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='Log Tracker Publisher ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Created Date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Entry Updated Date')),
                ('core_dsb_user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='ID of User From Danasaham Core')),
                ('publisher_company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('initial_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Initial Registration Date')),
                ('publisher_upgrade_date', models.DateTimeField(blank=True, null=True, verbose_name='Publisher Upgrade Date')),
                ('publisher_legal_data_input_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Publisher Legal Data Input Created Date')),
                ('publisher_finance_data_input_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Publisher Finance Data Input Created Date')),
                ('publisher_proposal_data_input_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Publisher Proposal Data Input Created Date')),
                ('primary_va_registration_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Primary VA Registration Registration Date')),
                ('va_operational_approval_created_date', models.DateTimeField(blank=True, null=True, verbose_name='VA Operational Approval Created Date')),
                ('approval_registration_fee_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Registration Fee Date')),
                ('primary_offering_input_date', models.DateTimeField(blank=True, null=True, verbose_name='Primary Offering Input Date')),
                ('confirmation_primary_offering_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Primary Offering Date')),
                ('cbestreporting_date', models.DateTimeField(blank=True, null=True, verbose_name='CBEST Reporting Date')),
                ('investation_succcess_sk_upload_date', models.DateTimeField(blank=True, null=True, verbose_name='Investation Succcess SK Upload Date')),
                ('investation_success_check_date', models.DateTimeField(blank=True, null=True, verbose_name='Investation Success Check Date')),
                ('investation_success_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Investation Success Approval Date')),
                ('investation_success_fund_transfer_date', models.DateTimeField(blank=True, null=True, verbose_name='Investation Success Fund Transfer Date')),
                ('investation_success_share_distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='Investation Success Share Distribution Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_tracker_publishers', related_query_name='log_tracker_publisher', to='core.document')),
                ('last_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_log_tracker_publishers', related_query_name='updated_log_tracker_publisher', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by User')),
            ],
        ),
    ]
