# Generated by Django 3.2.24 on 2024-07-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsb_user_publisher',
            name='coredsb_user_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='ID of User From Danasaham Core'),
        ),
    ]
