# Generated by Django 3.2.25 on 2024-06-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_first_name',
            field=models.TextField(blank=True, null=True, verbose_name='DTTOT First Name'),
        ),
    ]
