# Generated by Django 3.2.24 on 2024-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dsb_user_publisher_coredsb_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsb_user_personal',
            old_name='personal_spouse',
            new_name='personal_spouse_name',
        ),
        migrations.AddField(
            model_name='dsb_user_personal',
            name='personal_gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender of Personal (from Danasaham Core)'),
        ),
    ]
