# Generated by Django 3.2.24 on 2024-09-10 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log_tracker_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_tracker_corporate',
            fields=[
                ('log_tracker_corporate_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='Log Tracker Corporate ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Created Date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Entry Updated Date')),
                ('core_dsb_user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='ID of User From Danasaham Core')),
                ('corporate_company_name', models.CharField(blank=True, max_length=255, verbose_name='Corporate Name')),
                ('initial_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Initial Registration Date')),
                ('corporate_legal_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Corporate Legal Created Date')),
                ('corporate_finance_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Corporate Finance Created Date')),
                ('corporate_ksei_id_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Corporate KSEI ID Created Date')),
                ('corporate_info_check_date', models.DateTimeField(blank=True, null=True, verbose_name='Corporate Info Checking Date')),
                ('initial_primary_investment_date', models.DateTimeField(blank=True, null=True, verbose_name='Initial Primary Investment Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_tracker_corporates', related_query_name='log_tracker_corporate', to='core.document')),
                ('last_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_log_tracker_corporates', related_query_name='updated_log_tracker_corporate', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by User')),
            ],
        ),
    ]
