# Generated by Django 3.2.24 on 2024-09-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_log_tracker_corporate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_tracker_publisher',
            old_name='primary_va_registration_registration_date',
            new_name='primary_va_registration_date',
        ),
    ]
