version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb-danasaham-erp
      - DB_USER=devdanasaham
      - DB_PASS=danasaham!23
    env_file:
      - ./.env
    depends_on:
      - db

  smtp:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python -m aiosmtpd -n -l 0.0.0.0:8025"
    ports:
      - "8025:8025"
    volumes:
      - ./app:/app

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb-danasaham-erp
      - POSTGRES_USER=devdanasaham
      - POSTGRES_PASSWORD=danasaham!23
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=pg_trgm"]

volumes:
  dev-db-data: