# Generated by Django 3.2.25 on 2024-05-27 01:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('username', models.CharField(max_length=150, null=True, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=core.models.document_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('document_file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Document File Type (PDF, XLS, TEXT, or etc)')),
                ('document_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date when Document modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dttotDoc',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DTTOT Updated at')),
                ('dttot_id', models.TextField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dttot_first_name', models.TextField(blank=True, verbose_name='DTTOT First Name')),
                ('dttot_middle_name', models.TextField(blank=True, null=True, verbose_name='DTTOT Middle Name')),
                ('dttot_last_name', models.TextField(blank=True, null=True, verbose_name='DTTOT Last Name')),
                ('dttot_alias_name_1', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Name 1')),
                ('dttot_alias_first_name_1', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias First Name 1')),
                ('dttot_alias_middle_name_1', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Middle Name 1')),
                ('dttot_alias_last_name_1', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Last Name 1')),
                ('dttot_alias_name_2', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Name 2')),
                ('dttot_alias_first_name_2', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias First Name 2')),
                ('dttot_alias_middle_name_2', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Middle Name 2')),
                ('dttot_alias_last_name_2', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Last Name 2')),
                ('dttot_alias_name_3', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Name 3')),
                ('dttot_alias_first_name_3', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias First Name 3')),
                ('dttot_alias_middle_name_3', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Middle Name 3')),
                ('dttot_alias_last_name_3', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Last Name 3')),
                ('dttot_alias_name_4', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Name 4')),
                ('dttot_alias_first_name_4', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias First Name 4')),
                ('dttot_alias_middle_name_4', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Middle Name 4')),
                ('dttot_alias_last_name_4', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Last Name 4')),
                ('dttot_alias_name_5', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Name 5')),
                ('dttot_alias_first_name_5', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias First Name 5')),
                ('dttot_alias_middle_name_5', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Middle Name 5')),
                ('dttot_alias_last_name_5', models.TextField(blank=True, null=True, verbose_name='DTTOT Alias Last Name 5')),
                ('dttot_type', models.TextField(blank=True, null=True, verbose_name='DTTOT Type')),
                ('dttot_kode_densus', models.TextField(blank=True, null=True, verbose_name='DTTOT Kode Densus')),
                ('dttot_birth_place', models.TextField(blank=True, null=True, verbose_name='DTTOT Birth Place')),
                ('dttot_birth_date_1', models.TextField(blank=True, null=True, verbose_name='DTTOT Birth Date 1')),
                ('dttot_birth_date_2', models.TextField(blank=True, null=True, verbose_name='DTTOT Birth Date 2')),
                ('dttot_birth_date_3', models.TextField(blank=True, max_length=255, null=True, verbose_name='DTTOT Birth Date 3')),
                ('dttot_nationality_1', models.TextField(blank=True, max_length=255, null=True, verbose_name='DTTOT Nationality 1')),
                ('dttot_nationality_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='DTTOT Nationality 2')),
                ('dttot_domicile_address', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Domicile Address')),
                ('dttot_description_1', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Description 1')),
                ('dttot_description_2', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Description 2')),
                ('dttot_description_3', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Description 3')),
                ('dttot_description_4', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Description 4')),
                ('dttot_description_5', models.TextField(blank=True, max_length=4000, null=True, verbose_name='DTTOT Description 5')),
                ('dttot_nik_ktp', models.TextField(blank=True, null=True, verbose_name='DTTOT NIK KTP')),
                ('dttot_passport_number', models.TextField(blank=True, null=True, verbose_name='DTTOT Passport Number')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dttotDocs', related_query_name='dttotDoc', to='core.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
            ],
        ),
    ]
