# Generated by Django 3.2.25 on 2024-04-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('username', models.CharField(max_length=150, null=True, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, upload_to='documents/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('document_file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Document File Type (PDF, XLS, TEXT, or etc)')),
                ('document_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date when Document modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dttotDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DTTOT Updated at')),
                ('dttot_id', models.TextField(default=uuid.uuid4, editable=False)),
                ('_dttot_first_name', models.TextField(blank=True, verbose_name='DTTOT First Name')),
                ('_dttot_middle_name', models.TextField(blank=True, verbose_name='DTTOT Middle Name')),
                ('_dttot_last_name', models.TextField(blank=True, verbose_name='DTTOT Last Name')),
                ('dttot_type', models.CharField(max_length=50, verbose_name='DTTOT Type')),
                ('_dttot_domicile_address1', models.TextField(blank=True, verbose_name='DTTOT Domicile Address')),
                ('dttot_domicile_rt', models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile RT')),
                ('dttot_domicile_rw', models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile RW')),
                ('dttot_domicile_kelurahan', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Kelurahan')),
                ('dttot_domicile_kecamatan', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Kecamatan')),
                ('dttot_domicile_kabupaten', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Kabupaten')),
                ('dttot_domicile_kota', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Kota')),
                ('dttot_domicile_provinsi', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Provinsi')),
                ('dttot_domicile_postal_code', models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile Postal code')),
                ('dttot_domicile_country', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Country')),
                ('_dttot_description_1', models.TextField(blank=True, verbose_name='DTTOT Description 1')),
                ('_dttot_description_2', models.TextField(blank=True, verbose_name='DTTOT Description 2')),
                ('_dttot_description_3', models.TextField(blank=True, verbose_name='DTTOT Description 2')),
                ('dttot_description_4', models.TextField(blank=True, verbose_name='DTTOT Description 2')),
                ('dttot_description_5', models.TextField(blank=True, verbose_name='DTTOT Description 2')),
                ('_dttot_nik_ktp', models.TextField(blank=True, verbose_name='DTTOT NIK KTP')),
                ('_dttot_passport_number', models.TextField(blank=True, verbose_name='DTTOT Passport Number')),
                ('dtott_job', models.TextField(blank=True, verbose_name='DTTOT Job')),
                ('_dttot_work_number', models.TextField(blank=True, verbose_name='DTTOT Work Number')),
                ('_dttot_mobile_number', models.TextField(blank=True, verbose_name='DTTOT Mobile Number')),
                ('_dttot_home_number', models.TextField(blank=True, verbose_name='DTOTT Home Number')),
                ('_dttot_socialmedia_instagram', models.TextField(blank=True, verbose_name='DTTOT Instagram Accoun')),
                ('_dttot_socialmedia_facebook', models.TextField(blank=True, verbose_name='DTTOT Facebook Account')),
                ('_dttot_socialmedia_x', models.TextField(blank=True, verbose_name='DTTOT X account')),
                ('_dttot_organization_name', models.TextField(blank=True, verbose_name='DTTOT Organization Name')),
                ('_dttot_kartukeluarga_number', models.TextField(blank=True, verbose_name='DTTOT Nomor Kartu Keluarga')),
                ('dttot_domicile_city', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile City outside Indonesia')),
                ('dttot_domicile_district', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile District outside Indonesia')),
                ('dttot_domicile_subdistrict', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Subdistrict outside Indonesia')),
                ('_dttot_kode_densus', models.TextField(blank=True, verbose_name='DTTOT Densus Code')),
                ('dttot_birth_place_type', models.CharField(blank=True, max_length=50, verbose_name='DTTOT Type of Birth Place that we know (City, Country, etc)')),
                ('_dttot_birth_place', models.TextField(blank=True, verbose_name='DTTOT Birth Place')),
                ('_dttot_organization_created_by', models.TextField(blank=True, verbose_name='DTTOT PIC / Founder of Organization')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dttotDocs', related_query_name='dttotDoc', to='core.document')),
                ('input_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
            ],
        ),
    ]
