# Generated by Django 3.2.24 on 2024-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240213_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated_date',
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret_key',
            field=models.CharField(blank=True, help_text='A hex-encoded 20-byte secret key', max_length=40, null=True),
        ),
    ]
