# Generated by Django 3.2.24 on 2024-02-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240215_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifcation_code_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
