# Generated by Django 3.2.25 on 2024-04-17 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dttotdoc_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dttotdoc',
            name='id',
        ),
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_id',
            field=models.TextField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
