# Generated by Django 3.2.24 on 2024-02-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240222_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
