# Generated by Django 3.2.24 on 2024-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_totp_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='_totp_secret_key',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_otp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
