# Generated by Django 3.2.24 on 2024-02-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240223_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_totp_secret_key',
            new_name='totp_secret_key',
        ),
    ]
