# Generated by Django 3.2.24 on 2024-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dttotdoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='created_by',
            new_name='input_by',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='DTTOT_organization_created_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT PIC / Founder of Organization'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dtott_job',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Job'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_birth_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Birth Place'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_birth_place_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Type of Birth Place that we know (City, Country, etc)'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_description_1',
            field=models.TextField(blank=True, verbose_name='DTTOT Description 1'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_description_2',
            field=models.TextField(blank=True, verbose_name='DTTOT Description 2'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_description_3',
            field=models.TextField(blank=True, verbose_name='DTTOT Description 2'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_description_4',
            field=models.TextField(blank=True, verbose_name='DTTOT Description 2'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_description_5',
            field=models.TextField(blank=True, verbose_name='DTTOT Description 2'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_domicile_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile City outside Indonesia'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_domicile_country',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Country'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_domicile_district',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile District outside Indonesia'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_domicile_subdistrict',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Domicile Subdistrict outside Indonesia'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_home_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTOTT Home Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_kartukeluarga_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Nomor Kartu Keluarga'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_kode_densus',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Densus Code'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_mobile_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Mobile Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_nik_ktp',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT NIK KTP'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_organization_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Organization Name'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Passport Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_socialmedia_facebook',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Facebook Account'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_socialmedia_instagram',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Instagram Account'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_socialmedia_x',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT X account'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='dttot_work_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='DTTOT Work Number'),
        ),
    ]
