# Generated by Django 3.2.24 on 2024-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240301_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='dttot_description_1',
            new_name='_dttot_description_1',
        ),
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='dttot_description_2',
            new_name='_dttot_description_2',
        ),
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='dttot_description_3',
            new_name='_dttot_description_3',
        ),
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='dttot_domicile_address1',
            new_name='_dttot_domicile_address1',
        ),
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='dttot_kode_densus',
            new_name='_dttot_kode_densus',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='DTTOT_organization_created_by',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_birth_place',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_first_name',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_home_number',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_kartukeluarga_number',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_last_name',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_mobile_number',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_nik_ktp',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_organization_name',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_passport_number',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_socialmedia_facebook',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_socialmedia_instagram',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_socialmedia_x',
        ),
        migrations.RemoveField(
            model_name='dttotdoc',
            name='dttot_work_number',
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_DTTOT_organization_created_by',
            field=models.TextField(blank=True, verbose_name='DTTOT PIC / Founder of Organization'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_birth_place',
            field=models.TextField(blank=True, verbose_name='DTTOT Birth Place'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_first_name',
            field=models.TextField(blank=True, verbose_name='DTTOT First Name'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_home_number',
            field=models.TextField(blank=True, verbose_name='DTOTT Home Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_kartukeluarga_number',
            field=models.TextField(blank=True, verbose_name='DTTOT Nomor Kartu Keluarga'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_last_name',
            field=models.TextField(blank=True, verbose_name='DTTOT Last Name'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_mobile_number',
            field=models.TextField(blank=True, verbose_name='DTTOT Mobile Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_nik_ktp',
            field=models.TextField(blank=True, verbose_name='DTTOT NIK KTP'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_organization_name',
            field=models.TextField(blank=True, verbose_name='DTTOT Organization Name'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_passport_number',
            field=models.TextField(blank=True, verbose_name='DTTOT Passport Number'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_socialmedia_facebook',
            field=models.TextField(blank=True, verbose_name='DTTOT Facebook Account'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_socialmedia_instagram',
            field=models.TextField(blank=True, verbose_name='DTTOT Instagram Accoun'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_socialmedia_x',
            field=models.TextField(blank=True, verbose_name='DTTOT X account'),
        ),
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_work_number',
            field=models.TextField(blank=True, verbose_name='DTTOT Work Number'),
        ),
        migrations.AlterField(
            model_name='dttotdoc',
            name='dtott_job',
            field=models.TextField(blank=True, verbose_name='DTTOT Job'),
        ),
    ]
