# Generated by Django 3.2.24 on 2024-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240304_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dttotdoc',
            old_name='_DTTOT_organization_created_by',
            new_name='_dttot_organization_created_by',
        ),
        migrations.AlterField(
            model_name='dttotdoc',
            name='_dttot_kode_densus',
            field=models.TextField(blank=True, verbose_name='DTTOT Densus Code'),
        ),
    ]
