# Generated by Django 3.2.24 on 2024-03-04 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240304_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_id',
            field=models.TextField(default=uuid.uuid4, editable=False),
        ),
    ]
