# Generated by Django 3.2.24 on 2024-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_dttotdoc_dttot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_domicile_rt',
            field=models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile RT'),
        ),
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_domicile_rw',
            field=models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile RW'),
        ),
    ]
