# Generated by Django 3.2.24 on 2024-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240304_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttotdoc',
            name='dttot_domicile_postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='DTTOT Domicile Postal code'),
        ),
    ]
