# Generated by Django 3.2.24 on 2024-03-05 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_dttotdoc_dttot_domicile_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dttotdoc',
            name='id',
        ),
        migrations.AlterField(
            model_name='dttotdoc',
            name='document_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
