# Generated by Django 3.2.25 on 2024-03-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_dttotdoc_input_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_otp_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret_key',
        ),
    ]
