# Generated by Django 3.2.25 on 2024-03-14 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, upload_to='documents/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date when Document modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
