# Generated by Django 3.2.25 on 2024-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document File Type (PDF, XLS, TEXT, or etc)'),
        ),
    ]
