# Generated by Django 3.2.25 on 2024-03-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_document_document_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dttotdoc',
            name='_dttot_middle_name',
            field=models.TextField(blank=True, verbose_name='DTTOT Middle Name'),
        ),
    ]
