# Generated by Django 3.2.24 on 2025-05-27 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DttotDocReport',
            fields=[
                ('dttotdoc_report_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='DTTOT Doc Report ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DTTOT Doc Report Instruction Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='DTTOT Report Date')),
                ('status_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Doc Processing')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dttotDocReport', related_query_name='dttotDocReport', to='documents.document')),
            ],
            options={
                'verbose_name': 'DTTOT Document Report',
                'verbose_name_plural': 'DTTOT Document Reports',
                'db_table': 'dttotdoc_report',
                'ordering': ['-created_date'],
            },
        ),
    ]
