# Generated by Django 3.2.24 on 2025-05-27 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dttotDocReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dttotdocreport',
            name='last_update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dttotDocReports', related_query_name='updated_dttotDocReport', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by User'),
        ),
        migrations.AddIndex(
            model_name='dttotdocreport',
            index=models.Index(fields=['document'], name='idx_dttot_document'),
        ),
        migrations.AddIndex(
            model_name='dttotdocreport',
            index=models.Index(fields=['status_doc'], name='idx_dttot_status_doc'),
        ),
    ]
