# Generated by Django 3.2.24 on 2025-04-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dttotDocReport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DttotDocReportPersonal',
            fields=[
                ('dttotdoc_report_personal_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='DTTOT Doc Report Personal ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Created Date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Entry Updated Date')),
                ('dsb_user_personal', models.CharField(blank=True, max_length=255, verbose_name='Entry Personal User that matched with similarity > 0.8')),
                ('kode_densus_personal', models.CharField(blank=True, max_length=20, verbose_name='Entry Personal User that matched with similarity > 0.8')),
                ('score_match_similarity', models.FloatField(default=0.0, verbose_name='Similarity Score')),
                ('dttotdoc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reports', related_query_name='personal_report', to='dttotDocReport.dttotdocreport')),
                ('last_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dttotDoc_personals', related_query_name='updated_dttotDoc_personal', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by User')),
            ],
            options={
                'verbose_name': 'DTTOT Doc Report from User Personal',
                'verbose_name_plural': 'Multi DTTOT Doc Report from User Personal',
                'db_table': 'dttotdocreport_personal',
            },
        ),
    ]
