name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker-compose and docker commands
      - name: Set up Docker Compose
        run: |
          cd backend
          docker-compose down -v --rmi all --remove-orphans
          docker volume rm $(docker volume ls -q -f dangling=true) || true

      # Rebuild and start the services with Docker Compose
      - name: Rebuild the Docker Container with Docker Compose
        run: |
          cd backend
          docker-compose up -d --build

      # Create and adjust permissions for Custom Temporary Directory mirroring MEDIA_ROOT
      - name: Create Custom Temporary Media Directory and Set Permissions
        run: |
          docker-compose run --rm app sh -c "mkdir -p /app/media/test_media"
          docker-compose run --rm app sh -c "chown -R django-user:django-user /app/media"

      - name: Run Migrations
        run: |
          cd backend
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate"

      # Run tests
      - name: Test
        run: |
          cd backend
          docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: |
          cd backend
          docker-compose run --rm app sh -c "flake8"
