name: Checks

on: [push]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  test:
    needs: setup
    runs-on: ubuntu-20.04
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py migrate"

      - name: Run Tests
        run: cd backend && docker-compose run --rm app sh -c "python manage.py test"

  lint:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - name: Run Lint
        run: cd backend && docker-compose run --rm app sh -c "flake8"
