name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker-compose and docker commands
      - name: Set up Docker Compose
        run: |
          cd backend
          docker-compose down -v --rmi all --remove-orphans
          docker volume rm $(docker volume ls -q -f dangling=true) || true

      # Create and adjust permissions for Custom Temporary Directory mirroring MEDIA_ROOT
      - name: Create Custom Temporary Media Directory
        run: mkdir -p ${{ github.workspace }}/app/media/test_media

      - name: Adjust Permissions for Custom Temporary Media Directory
        run: chmod -R 777 ${{ github.workspace }}/app/media

      # Rebuild and start the services with Docker Compose
      - name: Rebuild the Docker Container with Docker Compose
        run: |
          cd backend
          docker-compose up -d --build

      - name: Run Migrations
        run: |
          cd backend
          docker-compose run --rm app sh -c "python manage.py wait_for_db"
          docker-compose exec -T devdb-danasaham-erp devdanasaham -U postgres -c 'ALTER SYSTEM SET enable_parallel_hash TO off;'
          docker-compose exec -T devdb-danasaham-erp devdanasaham -U postgres -c 'SELECT pg_reload_conf();'
          docker-compose run --rm app sh -c "python manage.py migrate"

      # Run tests
      - name: Test
        run: |
          cd backend
          docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: |
          cd backend
          docker-compose run --rm app sh -c "flake8"
